### ISSUE TITLE
button shows button 1 label

### ISSUE THREAD

**Issue by dkuss** [pkshetlie/RagnaCustomsApp#3]
In the Twitch bot tab the button at the bottom shows the label "button 1" instead of a correct label text.

**Comment by pkshetlie** [comment]
I think you get an old version, it now displays "refresh"

**Comment by dkuss** [comment]
Confirmed, sorry.
App needs an auto updater or at least a message when there is an update ;)

**Comment by pkshetlie** [comment]
it's a feature i want to add, but i don't know how to for now :s
