### ISSUE TITLE
App doesn't remember what has been downloaded

### ISSUE THREAD

**Issue by Rocksterdev** [pkshetlie/RagnaCustomsApp#39]
What the title pretty much says there is no persistence in charts you have already downloaded this could possibly even be checked by checking the custom songs folder just to mitigate people "downloading the same song twice" since it does discover them after "redownloading" the chart.

**Comment by pkshetlie** [comment]
Hi, did you set the API key in the app ?

**Comment by pkshetlie** [comment]
Hi, sorry I don't understand what you mean.
or maybe it's a bug due to the update to the last version, we have to change song folders name in the last version, so if you don't have delete all songs and redownload all i understand your issue

**Comment by Rocksterdev** [comment]
[here is a gif of the issue](https://i.imgur.com/7TbdSar.gif) I am trying to explain as you can see I have charts downloaded yet when you search for new charts everything comes back as "red" (Which I assume means not downloaded yet)

**Comment by pkshetlie** [comment]
Ho ! That's right, this feature is not available for now.
