### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by ExtremeTrash1** [pkshetlie/RagnaCustomsApp#41]
When I try to download a custom song it'll show me a pop up explaining that there is something wrong and to either quit or keep going. If I keep going it just stays like that and never downloads. Any solution? Thank you

**Comment by Chrisr0** [comment]
In your **"Documents"** folder create folder **"Ragnarock"** and inside create **"CustomSongs"**
It should look like this **Documents\Ragnarock\CustomSongs**
Worked for me
