### ISSUE TITLE
Quest 3 doesn't show up to sync

### ISSUE THREAD

**Issue by GregP-Navdna** [pkshetlie/RagnaCustomsApp#48]
I'm using a quest 3 and wasn't able to get the device to be found when attempting to sync the songs.
I've had to modify the code in the following function, and added what I saw the device was coming up when connected to my PC. I'm running windows 11. 
should I make a pull request for the change? 

      public static MediaDevice GetFirstFoundDevice()
      {
          var devices = MediaDevice.GetDevices();
          foreach (var d in devices)
              if (d.Description.ToLower().Contains("quest") || d.Description.ToLower().Contains("pico") || d.Description.ToLower().Contains("mtp")) //<---**this is what I added to get my quest 3 to be found.**
              {
                  DeviceSongDirectoryName = $@"\Android\data\com.wanadev.ragnarockquest\files\UE4Game\Ragnarock\Ragnarock\Saved\CustomSongs";
                  DeviceConfigDirectoryName = $@"\Android\data\com.wanadev.ragnarockquest\files\UE4Game\Ragnarock\Ragnarock\Saved\Config";
                  return d;
              }
          return null;
      }

**Comment by pkshetlie** [comment]
probably fixed with https://github.com/pkshetlie/RagnaCustomsApp/pull/49
